### PR TITLE
NEW: Adding getTableForField(): Ability to infer the actual DataObject that a particular field lives on (at runtime).

### PR DESCRIPTION
**Pull request by patricknelson**
Adding getTableForField(): Ability to infer the actual DataObject that a particular field lives on (at runtime).

### CODE REVIEW

**Comment by michalkleiner** [comment]
https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DataObjectSchema.php#L682 already exists in the framework, so no need to implement it through a custom code, @patricknelson.

```
$table = DataObjectSchema::singleton()->tableForField($class, $field);
```

**Comment by patricknelson** [comment]
This module is only officially compatible with the outdated SilverStripe v3, however: We should add an issue to address this when we eventually upgrade this module to SS v4. 🙂

**Comment by patricknelson** [comment]
Then again I could just remove this method since I don’t use it myself and there’s no sense in creating an API that would need to break after upgrade. 🤔 I originally just added it to keep the code but move it out of my custom site codebase.

**Comment by patricknelson** [comment]
I think it’s too late for that now. @michalkleiner, I actually didn’t realize anyone was actually using this module still. I’ll avoid breaking changes and just strip it out in v4 update (or v1 of this module). Sorry for the confusion!

**Comment by michalkleiner** [comment]
Ah, right, didn't realise it wasn't SS4 compatible. We don't actively use it, I'm just watching ;-)

**Comment by patricknelson** [comment]
I still use it regularly and definitely plan on eventually migrating it to SS v4 when I can finally get my site to that point. It’ll be a long path since it’s a huge site, but it’s definitely happening. Eventually… 😊

**Pull request merged**
